version: '3'

services:
  springboot-docker-compose-app-container:
    image: ao3-v2-image:ao3-tag
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/ao3-server
      - .:/code
    ports:
     - "8081:8080"
